### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by olivierp99** [nv-nguyen/template-pose#1]
On T-LESS [14], we follow the protocol of [31] by using a dense regular icosahedron with 2’536 viewpoints and
36 in-plane rotations for each rendered image. Altogether,
this yields 92’232 templates per object.

it should be 2562 and not 2536

have a nice day

**Comment by nv-nguyen** [comment]
Hi Olivier,
Yes, it's 2562, not 2536. I will update it in the next version.
Many thanks for pointing this out!
--Nguyen
