### ISSUE TITLE
ask about process_gt_linemod

### ISSUE THREAD

**Issue by kgmin156** [nv-nguyen/template-pose#10]
Hello author!

Thanks for the interesting paper!!

I'm a little confused in **process gt linemod** code
in **process_linemod** function, you define the all_poses = ['cam_R_w2c: , 'cam_t_w2c']
**If I use the synthetic data generated by blenderproc**, Can I use the cam_R_w2c and cam_t_w2c in scene_camera.json?
And I wonder that is it okay to use **cam pose related with world**(cam_R_w2c and cam_t_w2c)? I think it is not accurate object's 6D pose.

**Comment by nv-nguyen** [comment]
So sorry for my very late response. I updated the codebase and added a demo, please check it out.
All the poses are defined in the same convention as BOP challenge and you can use [this function](https://github.com/nv-nguyen/template-pose/blob/main/src/dataloader/base.py#L292) to double-check the poses. Feel free to re-open this issue if needed!
