### ISSUE TITLE
train_linemod.py

### ISSUE THREAD

**Issue by shqmffl486** [nv-nguyen/template-pose#11]
Hello!!
@nv-nguyen 

I'm sorry I kept asking you questions..
I want to train with my synthetic data!!

I'm going to train by adding 4 new models. But the comments (this is problem)
"seen
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
INFO:LM_ResNet50_split1:Epoch-78, seen -- Mean err: nan, Acc: 0.00, Rec : 0.93, Class and Pose  : 0.00
INFO:LM_ResNet50_split1:Validation time for epoch 78: 0.57 minutes "

And

-> like this!
and no warnings in this comment (this is okay)
"Saving to /home/mount4t/template-pose_1/root/results/weights/LM_ResNet50_split1/model_epoch77.pth
 98%|██████████████████████████████████████████████████████████████████████████████████▉  | 78/80 [13:57:56<21:28, 644.07s/it]INFO:LM_ResNet50_split1:Epoch-78 -- Iter [1/1528] loss: 0.00, (pos: 0.81, neg: 0.05)
INFO:LM_ResNet50_split1:Epoch-78 -- Iter [10/1528] loss: 0.00, (pos: 0.86, neg: 0.05)
INFO:LM_ResNet50_split1:Epoch-78 -- Iter [20/1528] loss: 0.00, (pos: 0.82, neg: 0.03)
INFO:LM_ResNet50_split1:Epoch-78 -- Iter [30/1528] loss: 0.17, (pos: 0.83, neg: 0.07) "

So.... what does "WARNING:root:NaN or Inf found in input tensor." mean?

**Comment by nv-nguyen** [comment]
So sorry for my very late response. Can you share the data that you are using? I've never had this "NaN" problem.
Also, I updated the codebase and added a demo, please check it out.
