### ISSUE TITLE
How to achieve “crop_frame”

### ISSUE THREAD

**Issue by BraveBoBo** [nv-nguyen/template-pose#12]
I used my own dataset but could not complete the clipping. The camera's internal parameter matrix has been replaced, but it still cannot be implemented. Please how to crop_frame

**Comment by nv-nguyen** [comment]
So sorry for my very late response. I updated the codebase and added a demo, please check it out. 
"crop_frame" is not needed anymore. Feel free to re-open or create an new issue if needed!
