### ISSUE TITLE
some questions about paper

### ISSUE THREAD

**Issue by helloyuning** [nv-nguyen/template-pose#14]
Hello, author

Thanks for your greate work and code sharing

I have some questions about the paper:

1. The paper said that the similarity between the RGB image and the Template is calculated by grid, and then the result with the highest similarity is returned. Is this grid custom? If yes, how to define it?
2. Does the model predict a matrix? How to get the predicted identity and pose?

Thanks, 
yuning

**Comment by nv-nguyen** [comment]
Hi @helloyuning,

1. The features grid is calculated from ResNet backbone which transform an input image 3xHxW to Cx(H/8)x(W/8).
2. Each template is annotated with identity and pose, the model predicts the nearest template so it can return both identity and pose.

Hope It will be helpful!

Nguyen
