### ISSUE TITLE
About calculate_score

### ISSUE THREAD

**Issue by qifengluo** [nv-nguyen/template-pose#15]
Hi,  I find somthing of calculate_score function in test_utils.py, it writes
cosine_sim_sym = F.cosine_similarity(gt_location_opposite, gt_location_opposite)
gt_location_opposite compares with itself, it always is  1.

**Comment by nv-nguyen** [comment]
Hi @qifengluo,
Thanks for pointing it out! I had found this error but forgot to update it. 
All the codebase is being updated and this function calculate_score was also fixed. Please check [this file](https://github.com/nv-nguyen/template-pose/blob/main/src/model/loss.py) for more detail.
