### ISSUE TITLE
Can you share the inference code

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [nv-nguyen/template-pose#17]
Hello @nv-nguyen 

Can you please provide an inference script that can work on RGB images and unseen objects?

thanks.

**Comment by nv-nguyen** [comment]
Hello, 
Yes, I will add a gradio demo and a tutorial to show how we can test on custom objects soon.

**Comment by nv-nguyen** [comment]
A demo has been added to the repo. Feel free to re-open this issue if needed!
