### ISSUE TITLE
is gradio_demo.py complete?

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [nv-nguyen/template-pose#18]
@nv-nguyen is gradio_demo.py completed or are you working on it? It seems to be incomplete to me.

**Comment by nv-nguyen** [comment]
Sorry, it is not completed yet. You can check out [this colab](https://colab.research.google.com/drive/18Si4X7fcKFHvFuMS-FRVkDyTvlOsr78H?usp=sharing) demo meanwhile.

**Comment by Harsh-Vavaiya** [comment]
It's okay, thanks.
