### ISSUE TITLE
A question about the definition of global/local

### ISSUE THREAD

**Issue by 63445538** [nv-nguyen/template-pose#2]
Hi Van-Nguyen,

Thank you for your excellent work!

I am a little confused by the definition of global or local in the paper. The paper points out that [2] employs global features, but both methods use the local patch as input to train and inference. So, could you give a clearer introduction about the global/local feature you used in the experiments? Thank you.

Regards,
Rui

**Comment by nv-nguyen** [comment]
Hi Rui,

Thank you for your interest in our paper!

Indeed, two methods use GT pose/bounding box to crop the input image to get a patch focusing on an object of interest. We distinguish two representations:

1. Global representation: representing input cropped image as a 1D embedding (by applying pooling layers as in [2]).
2. Local representation: representing input cropped image as a 3D tensor. 

The global/local here are defined w.r.t to the input cropped image (not the whole image containing all objects).

Hope it will be clearer for you!

--Nguyen

**Comment by nv-nguyen** [comment]
Hi,
The code is now released, you can see why we call them global or local representations. I close the issue if there is no more question.
Feel free to reopen it again!
--Nguyen
