### ISSUE TITLE
can't download lm dataset

### ISSUE THREAD

**Issue by LucasQAQ** [nv-nguyen/template-pose#21]
Hi, @nv-nguyen, I want to download the processed BOP datasets. But when I run ./src/scripts/download_and_process_datasets.sh., I find the url of LINEMOD https://files.icg.tugraz.at/f/472f5d1108/?dl=1 is not found

**Comment by nv-nguyen** [comment]
Sorry for late replies. 

I used this url since I did not know that the ground-truth is also released in [BOP datasets](https://bop.felk.cvut.cz/datasets/). You can download directly from BOP datasets instead and it will not require any processing since the mesh I used is also from BOP.
