### ISSUE TITLE
About the evaluation of tless dataset

### ISSUE THREAD

**Issue by qifengluo** [nv-nguyen/template-pose#23]
Hi, 
I see that there is a program for calculating vsd in the project, namely vsd.py and vsd_ Utils.py. But I want to use the BOP toolkit for evaluation. So I would like to ask whether it is correct to set params of eval_bop19_pose.py in BOP toolkit according to vsd params in paper: setting 'vsd_taus': list([20]),'correct_th': [[0.3]],'visib_gt_min': 0.1(line 39,41,58)
Thanks  a lot.

**Comment by nv-nguyen** [comment]
<img width="565" alt="image" src="https://github.com/nv-nguyen/template-pose/assets/54082176/85178248-7c91-49d4-ba25-ca00cd6fb3f4">

Sorry for late replies. 

Yes, this is correct. I followed [MultiPath paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Sundermeyer_Multi-Path_Learning_for_Object_Pose_Estimation_Across_Domains_CVPR_2020_paper.pdf). You can check their code if needed!
