### ISSUE TITLE
3D Bounding box visualization

### ISSUE THREAD

**Issue by DhruvMakwana** [nv-nguyen/template-pose#24]
Thanks for this amazing Repository. 

Can you help me with how to draw 3D Bounding box from 3x3 pose matrix for visualization.

**Comment by nv-nguyen** [comment]
I have [bop_viz_kit](https://github.com/nv-nguyen/bop_viz_kit) to visualize 3D bounding box, 3D axis, etc. You can use [this function](https://github.com/nv-nguyen/bop_viz_kit/blob/main/bop_viz_kit/utils/vis.py#L10) to visualize 3D box.
