### ISSUE TITLE
inference on custom object gradio timeline

### ISSUE THREAD

**Issue by monajalal** [nv-nguyen/template-pose#25]
Awesome job! Any chance you may be able to predict your timeline for releasing the gradio for custom object inference?

![image](https://github.com/nv-nguyen/template-pose/assets/1892917/fbe10200-3e11-4351-a252-febd1a244faa)

**Comment by nv-nguyen** [comment]
I planned to do a gradio demo but it seems not easy to input 3D model and render using gradio so I end up with a [Colab demo](https://colab.research.google.com/drive/18Si4X7fcKFHvFuMS-FRVkDyTvlOsr78H?usp=sharing) instead. 

I removed the gradio section in README to be less confusing.

**Comment by monajalal** [comment]
@nv-nguyen  Thank you so much for your response. This is very helpful. I will be in touch.
