### ISSUE TITLE
notebook for novel object pose of custom (not in famous 6D pose datasets) objects

### ISSUE THREAD

**Issue by monajalal** [nv-nguyen/template-pose#26]
Would you please point to a notebook that contains extracting the novel pose of a custom object that is not present in famous 6D pose datasets such as T-LESS, LMO, YCB, etc?

I would like to know what are the minimum requirements for getting inference for a novel custom object that is not present in training.
https://github.com/nv-nguyen/template-pose/issues/3#issuecomment-1173322044

For example, in media folder, for the colab notebook, I do notice you have 3 rgb photos and a ply mesh file. Is that what needed? 

I think I am a bit confused because your paper states: **"It relies on a small set of training objects
to learn local object representations, which allow us to locally match the input image to a set of “templates”, rendered images of the CAD models for the new objects. "**

If you could provide a new notebook that showcases novel custom object pose estimation would be really amazing.

**Comment by nv-nguyen** [comment]
We provide a demo in colab showing how it can be run. If you want to try on your custom objects, you can try it and open issues here if there is any issue related to the code
