### ISSUE TITLE
add 6D pose (or 3D pose) visualization code to colab demo notebook

### ISSUE THREAD

**Issue by monajalal** [nv-nguyen/template-pose#28]
Could you please add visualization code to overlay the 6D pose on top of the best template pose on image end of your colab notebook after we get the pose matrix?

![image](https://github.com/nv-nguyen/template-pose/assets/1892917/a8b3350c-1e85-4c99-92a3-df0395985f4d)

For example, could you please show how to use https://github.com/nv-nguyen/bop_viz_kit/blob/main/bop_viz_kit/utils/vis.py#L10 here?
https://github.com/nv-nguyen/template-pose/issues/24

`def draw_bounding_box(cvImg, obj_openCV_pose, bbox, intrinsic, color, thickness):`

From lm dataset, we have:

```
{
  "cx": 325.2611,
  "cy": 242.04899,
  "depth_scale": 1.0,
  "fx": 572.4114,
  "fy": 573.57043,
  "height": 480,
  "width": 640
}
```

for `/home/mona/data/BOP/lm/lm/camera.json` file which we can use for intrinsic.

which we also have 
```
"0": {"cam_K": [572.4114, 0.0, 325.2611, 0.0, 573.57043, 242.04899, 0.0, 0.0, 1.0], "depth_scale": 1.0},

```

in `(base) mona@ada:~/data/BOP/lm/lm$ vi test/000006/scene_camera.json` file

I am also not sure what image is exactly the one below, it wasn't the following from cat category.
![image](https://github.com/nv-nguyen/template-pose/assets/1892917/75eb846f-1d7f-4ab0-a9d1-52a795767cd6)

(base) mona@ada:~/data/BOP/lm/lm$ feh test/000006/rgb/000002.png 

could you please help with this?

further how do you access bbox for calling `draw_bounding_box` function?

**Comment by nv-nguyen** [comment]
I have a tool to visualize bounding box [here](https://github.com/nv-nguyen/bop_viz_kit).
