### ISSUE TITLE
overlaying the best predicted_template on query image

### ISSUE THREAD

**Issue by monajalal** [nv-nguyen/template-pose#29]
Somehow this code does a weird job of visualizing. Would you have any suggestion for better visualization?

```
query_image = query_tensor.squeeze().permute(1, 2, 0).numpy().astype(np.uint8)

first_template = predicted_templates[0]

template_image = (first_template * 255).permute(1, 2, 0).numpy().astype(np.uint8)


overlay_image = cv2.addWeighted(query_image, 0.3, template_image, 0.7, 0)


plt.imshow(overlay_image)
plt.axis('off')
plt.show()
```

![image](https://github.com/nv-nguyen/template-pose/assets/1892917/9b9b05be-e149-4df7-b8f7-fcf7108844da)

**Comment by nv-nguyen** [comment]
Did you double-check by showing template_image and query_image? 
Closing this issue since it is not related to this repo.
