### ISSUE TITLE
Documentation for template_pose_checkpoint.ckpt

### ISSUE THREAD

**Issue by nino-0000** [nv-nguyen/template-pose#30]
Hi,
thanks for the exciting and easy-to-read paper and repo!

The `template_demo.ipynb` notebook makes use of `template_pose_checkpoint.ckpt` from [gdrive](https://drive.google.com/drive/folders/1p9eJ8dTxR3rVinvaFxPw5N_3IGSlS2_E). I couldn't find any documentation for this checkpoint, could you please give some information on how/with which datasets/how long this was trained?

Thank you!

**Comment by nv-nguyen** [comment]
Good question! I updated new features for the codebase in May and use all the real-world images from BOP challenge that are not in in the test sets (LM-O, T-LESS) as training sets. This is done in [this line](https://github.com/nv-nguyen/template-pose/blob/main/train.py#L91) and [this config](https://github.com/nv-nguyen/template-pose/blob/main/configs/data/all.yaml). 

As I mentioned in README, if you don't want to use the new features and want to have exact the same config/results in the paper, you can use this command to go back `git checkout 50a1087`
