### ISSUE TITLE
Where to get source code for generating poses for creating templates

### ISSUE THREAD

**Issue by jerinka** [nv-nguyen/template-pose#31]
Link provided for same is broken. Could you please provide a valid link, for generating poses to generate templates.

**Comment by nv-nguyen** [comment]
Can you detail which link so that I can fix it?

**Comment by nv-nguyen** [comment]
The poses to generate templates are available [here](https://github.com/nv-nguyen/template-pose/tree/main/src/poses/predefined_poses)

**Comment by jerinka** [comment]
oops I am sorry, I meant to raise issue in megapose repo.
