### ISSUE TITLE
half_sphere_level2_and_level3.npy

### ISSUE THREAD

**Issue by shqmffl486** [nv-nguyen/template-pose#8]
hello author!!

I'm going to train a new 3D model by putting it in an existing dataset. Should I modify the half_sphere_level2_and_level3.npy file? How can I open the file? help plz!

**Comment by nv-nguyen** [comment]
Hi @shqmffl486,

You can open this file with np.load() like I did [here](https://github.com/nv-nguyen/template-pose/blob/ce1ffead1887b54efc8031e8e2442ba884e512ec/lib/datasets/tless/inout.py#L51) 

Please take a look at issue #6 if you want to generate predefined poses yourself.

Hope it will be helpful!

--Nguyen
