### ISSUE TITLE
LINEMOD.json

### ISSUE THREAD

**Issue by shqmffl486** [nv-nguyen/template-pose#9]
Hello author!

can i ask something..
so i run "python -m data.create_dataframe_linemod" this commend.
but results like this (in linemod.json)

 "real_location": [
        [
            NaN,
            NaN,
            NaN
        ],
        [
            NaN,
            NaN,
            NaN
        ],
        [
            NaN,
            NaN,
            NaN
        ],
        [
            NaN,
            NaN,
            NaN
        ],
        [
            NaN,
            NaN,

this results because of BlenderProc or blender version???????????????

**Comment by shqmffl486** [comment]
plz..

**Comment by nv-nguyen** [comment]
Hi @shqmffl486,

The "real_location" is the position of camera in the 3D sphere and it is calculated from the GT data for evaluation. So I don't think that it's from Blender or BlenderProc version.

You can use the provided LINEMOD.json if needed.

--Nguyen

**Comment by shqmffl486** [comment]
> 소유자

@nv-nguyen 

hello!
I re-set the environment and it seems that the composite data added to the LINEMOD.json file is included. 
Is it possible to train from the synthetic dataset I made? Do I really need LINEMOD.json?
